[package]
name = "BeanDesk"
version = "0.1.0"
description = "BeanDesk desktop shell"
license = "AGPL-3.0-only"
repository = "https://github.com/SuperDaniel-cn/BeanDesk"
edition = "2024"
rust-version = "1.90"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.7.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.12.1", features = [] }
tauri-plugin-log = "2"
tauri-plugin-http = "2"
tauri-plugin-store = "2"
tauri-plugin-dialog = "2"
libc = "0.2.189"
sys-locale = "0.3.2"
time = { version = "0.3.55", features = ["formatting", "local-offset", "macros"] }
tauri-plugin-updater = "2.13.1"
tauri-plugin-process = "2.4.0"
url = "2.5.8"
git2 = { version = "0.21.0", default-features = false }
